### ISSUE TITLE
Taxonomy IDs not matching for species XXX: (216819	190338)

### ISSUE THREAD

**Issue by B-1991-ing** [acvill/bracken_plot#2]
Dear bracken_plot development team,

One error occurred during processing **Family** and **Genus** level files.

Processing Output File 1_F_nt.bracken:: Sample 3
Taxonomy IDs not matching for species Xylophagaidae: (92613	183505)
PROGRAM START TIME: 02-02-2023 21:27:09
Processing Output File 10_G_nt.bracken:: Sample 1
Taxonomy IDs not matching for species Cyclophora: (216819	190338)
PROGRAM START TIME: 02-02-2023 21:27:09

Do you have any idea how to deal with this problem?

Best,

Bing

**Comment by acvill** [comment]
Thanks for using bracken_plot, Bing.

Unfortunately, your issue seems to be a problem with Bracken and not the bracken_plot app. I see you also opened an issue over on the Bracken repository.

https://github.com/jenniferlu717/Bracken/issues/214

I hope they respond to you soon. In the interim, you can try [installing a different version of Bracken via conda](https://anaconda.org/bioconda/bracken/files) to see if that solves your issues.
